In [16]:
from statsbombpy import sb
import pandas as pd
import numpy as np

competitions = sb.competitions()
competitions

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2025-07-28T14:19:20.467348,2025-07-29T16:03:07.355174,2025-07-29T16:03:07.355174,2025-07-28T14:19:20.467348
72,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
73,72,107,International,Women's World Cup,female,False,True,2023,2025-07-14T10:07:06.620906,2025-07-14T10:10:27.224586,2025-07-14T10:10:27.224586,2025-07-14T10:07:06.620906
74,72,30,International,Women's World Cup,female,False,True,2019,2024-08-08T15:57:56.748740,2021-06-13T16:17:31.694,None,2024-08-08T15:57:56.748740

In [17]:
competitions[(competitions["season_name"] == "2023/2024") | (competitions["season_name"] == "2024")]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
21,223,282,South America,Copa America,male,False,True,2024,2024-11-04T16:15:34.886972,None,None,2024-11-04T16:15:34.886972
68,55,282,Europe,UEFA Euro,male,False,True,2024,2024-09-28T16:51:20.698794,2025-03-24T14:12:30.785094,2025-03-24T14:12:30.785094,2024-09-28T16:51:20.698794

We will use the **2024 Copa America and UEFA Euro** competitions to find clusters of playstyle.

In [18]:
matchesEuro = sb.matches(competition_id=55, season_id=282)
matchesCopaAmerica = sb.matches(competition_id=223, season_id=282)

In [19]:
def circular_mean(angles):
    return np.arctan2(
        np.mean(np.sin(angles)),
        np.mean(np.cos(angles))
    )

def avg_angle(df):
    if len(df) == 0:
        return np.nan
    return circular_mean(df["pass_angle"])

def extract_features(events, team_name):
    features = {}

    # location extraction
    events = events[events["location"].notnull()].copy()
    events["x"] = events["location"].apply(lambda loc: loc[0])

    # split team vs opponent
    team_events = events[events["team"] == team_name]
    opp_events = events[events["team"] != team_name]

    passes = team_events[team_events["type"] == "Pass"]
    shots = team_events[team_events["type"] == "Shot"]
    carries = team_events[team_events["type"] == "Carry"]
    pressures = team_events[team_events["type"] == "Pressure"]
    deep = team_events[team_events["x"] < 40]
    mid = team_events[(team_events["x"] >= 40) & (team_events["x"] < 80)]
    final = team_events[team_events["x"] >= 80]


    # defensive actions
    def_actions = team_events[
        team_events["type"].isin([
            "Pressure", 
            "Duel", 
            "Interception", 
            "Foul Committed"
        ])
    ]

    # opponent passes (for PPDA)
    opp_passes = opp_events[opp_events["type"] == "Pass"]

    # Apply pressing zone filter (x < 80)
    def_actions = def_actions[def_actions["x"] < 80]
    opp_passes = opp_passes[opp_passes["x"] < 80]


    features["passes"] = len(passes)
    features["shots"] = len(shots)
    features["pressures"] = len(pressures)
    features["carries"] = len(carries)
    
    features["xg"] = (
        shots["shot_statsbomb_xg"].sum()
        if "shot_statsbomb_xg" in shots.columns else 0
    )

    features["average_pass_length"] = (
        passes["pass_length"].mean() if len(passes) > 0 else 0
    )

    features["ppda"] = (
        len(opp_passes) / len(def_actions)
        if len(def_actions) > 0 else np.nan
    )

    features["avg_pass_angle_deep"] = avg_angle(deep[deep["type"] == "Pass"])
    features["avg_pass_angle_mid"] = avg_angle(mid[mid["type"] == "Pass"])
    features["avg_pass_angle_final"] = avg_angle(final[final["type"] == "Pass"])

    return features

In [ ]:
import warnings
warnings.filterwarnings("ignore")

from tqdm import tqdm

rows = []

matches = pd.concat([matchesCopaAmerica, matchesEuro], ignore_index=True)

for match_id in tqdm(matches.match_id):

    events = sb.events(match_id=match_id)

    teams = events["team"].dropna().unique()

    for team in teams:

        features = extract_features(events, team)

        features["team"] = team
        features["match_id"] = match_id

        rows.append(features)

df = pd.DataFrame(rows)

df.head()

100%|██████████| 83/83 [01:03<00:00,  1.30it/s]

,passes,shots,pressures,carries,xg,average_pass_length,ppda,avg_pass_angle_deep,avg_pass_angle_mid,avg_pass_angle_final,team,match_id
0,537,11,155,413,1.082702,20.786734,3.128655,-0.042155,-0.046114,-0.023094,Argentina,3943077
1,659,19,161,527,0.988178,21.512906,2.338624,-0.034995,-0.128787,1.816389,Colombia,3943077
2,378,19,148,287,6.205310,21.140958,2.108844,-0.107044,0.033943,-0.629554,Canada,3943076
3,365,16,178,290,4.650427,23.869265,1.385417,-0.124896,0.032662,0.152638,Uruguay,3943076
4,460,11,154,364,0.754564,21.812680,1.252688,-0.147674,-0.093207,-0.566419,Uruguay,3942852

In [21]:
df.drop(columns=["match_id"], inplace=True)
df.to_csv(r"../data/matchwise_stats.csv", index=False)

In [22]:
team_stats = df.groupby("team").mean(numeric_only=True).reset_index()

In [23]:
team_stats

,team,passes,shots,pressures,carries,xg,average_pass_length,ppda,avg_pass_angle_deep,avg_pass_angle_mid,avg_pass_angle_final
0,Albania,392.666667,10.666667,146.666667,322.333333,0.727870,21.152318,3.315112,-0.079853,-0.161259,1.125253
1,Argentina,559.666667,14.666667,133.666667,456.666667,2.673967,20.898589,2.424673,0.003169,-0.017089,-1.030759
2,Austria,517.500000,12.500000,180.500000,415.500000,1.528953,20.446254,2.142054,0.142069,0.010456,-0.161990
3,Belgium,551.750000,13.250000,109.750000,471.750000,1.094532,20.983358,3.320037,-0.195753,-0.129669,0.369445
4,Bolivia,408.000000,5.666667,164.000000,315.333333,0.329439,21.921076,2.087439,-0.058614,-0.425858,-0.465007
5,Brazil,530.000000,13.750000,137.000000,438.750000,2.371144,20.577336,2.026312,0.150315,-0.169108,-1.144768
6,Canada,412.000000,12.333333,161.333333,317.666667,2.586989,21.194503,2.279355,0.027886,-0.112432,-0.386921
7,Chile,439.000000,7.333333,154.333333,348.333333,0.536587,23.249089,2.314058,-0.075030,-0.091201,0.189099
8,Colombia,492.000000,13.166667,138.666667,375.166667,1.561297,22.336315,2.272290,-0.010857,0.095794,0.219009
9,Costa Rica,300.333333,3.000000,173.333333,224.666667,0.158028,24.756273,2.371913,-0.082550,0.269005,0.531436
10,Croatia,595.000000,14.333333,182.000000,503.333333,1.941311,18.478528,2.180253,0.067208,0.350367,0.286351
11,Czech Republic,369.000000,14.666667,138.333333,277.666667,1.530181,23.841183,2.575063,0.062454,-0.051551,-0.840317
12,Denmark,590.250000,13.000000,140.250000,468.750000,0.967399,19.269141,3.080673,0.016432,-0.105756,-0.148155
13,Ecuador,330.750000,13.500000,131.000000,252.500000,1.973891,25.482300,2.253857,0.073904,-0.245513,-0.340957
14,England,648.571429,11.571429,126.571429,544.285714,1.501240,20.664633,3.326150,0.120615,0.115270,-1.289965
15,France,575.500000,16.833333,134.500000,482.000000,2.018681,19.274141,3.547792,0.062120,-0.210936,0.346633
16,Georgia,356.250000,7.500000,128.500000,292.000000,1.054265,21.583594,2.572272,0.087191,-0.075277,-0.300248
17,Germany,680.400000,19.000000,141.400000,589.400000,1.745140,18.238659,2.484322,-0.044622,0.051925,-0.727530
18,Hungary,408.666667,10.333333,176.333333,286.000000,1.110631,21.982581,2.502597,-0.075399,-0.267618,0.109553
19,Italy,625.750000,11.250000,147.000000,523.250000,0.826062,18.631291,3.214736,0.043933,0.012975,2.335439
20,Jamaica,381.333333,9.333333,110.333333,285.666667,0.702830,24.102249,2.357586,0.152753,0.041419,0.370505
21,Mexico,516.333333,19.333333,132.333333,391.333333,1.486010,21.061298,1.972912,0.053107,-0.270285,-0.468751
22,Netherlands,519.500000,13.833333,108.000000,421.166667,1.219747,19.808072,3.077778,0.005548,-0.072751,-1.031312
23,Panama,450.750000,12.500000,118.500000,363.750000,0.805546,22.810936,2.701787,0.128183,-0.006924,-0.179046
24,Paraguay,427.000000,14.333333,157.666667,341.666667,0.986445,21.786090,2.259826,-0.061818,-0.380452,0.328682
25,Peru,326.666667,7.666667,158.666667,234.333333,0.473446,23.956195,2.601064,-0.002786,0.105447,0.904848
26,Poland,396.666667,12.333333,157.333333,325.666667,1.175046,19.211352,2.207285,-0.071360,0.164500,0.303449
27,Portugal,774.000000,19.000000,129.600000,659.000000,2.941869,18.915914,2.535422,-0.100478,0.052575,0.634823
28,Romania,336.750000,9.500000,137.500000,243.500000,0.939182,23.017690,2.851378,-0.120124,0.100047,-0.088336
29,Scotland,410.666667,5.666667,137.000000,301.333333,0.338648,22.434817,2.713864,0.108759,-0.362877,0.836975
30,Serbia,558.666667,8.666667,129.000000,442.333333,0.678393,21.278711,3.046499,-0.057199,0.092759,0.352548
31,Slovakia,501.500000,12.500000,133.250000,383.250000,0.956472,21.718780,3.471364,-0.078424,-0.215019,0.334834
32,Slovenia,344.000000,10.000000,184.250000,250.000000,1.437378,23.401664,2.606020,0.022314,-0.134887,-1.731848
33,Spain,619.285714,17.571429,161.142857,531.571429,1.510639,19.929209,2.651002,0.034611,-0.009801,0.673289
34,Switzerland,509.600000,12.400000,165.200000,422.000000,1.696754,19.699792,2.775726,0.041791,-0.003591,-0.950573
35,Turkey,489.000000,14.400000,126.200000,402.800000,1.292925,20.427201,2.740044,0.061505,-0.033876,-1.192329
36,Ukraine,497.000000,13.333333,139.666667,418.333333,0.994767,21.257297,2.578845,-0.095122,-0.024698,-0.734069
37,United States,395.000000,11.333333,120.333333,272.666667,1.263320,24.987903,2.716666,0.081437,0.215364,0.521954
38,Uruguay,406.666667,15.666667,164.500000,321.333333,2.484375,23.116903,1.691583,-0.094659,-0.069918,-0.316010
39,Venezuela,456.000000,15.500000,131.000000,336.000000,2.515282,22.587498,2.290010,-0.088022,-0.084348,0.859896

In [24]:
team_stats.to_csv(r'../data/team_stats_raw.csv', index=False)